/**
 * A logger function that will only logs on development
 * @param object - The object to log
 * @param comment - Autogenerated with `lg` snippet
 */
export default function logger(object: unknown, comment?: string): void {
  if (process.env.NODE_ENV === 'production') return;

  console.log(
    '%c ============== INFO LOG \n',
    'color: #22D3EE',
    `${window.location.pathname}\n`,
    `=== ${comment ?? ''}\n`,
    object,
  );
}
