services:
  postgres:
    container_name: container-postgres
    image: postgres
    hostname: localhost
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: stats
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    container_name: container-pgadmin
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    restart: unless-stopped

  backend:
    container_name: container-backend
    build:
      context: ./backend
    restart: always
    environment:
      PORT: 3001
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: root
      DB_NAME: stats
    ports:
      - 3001:3001

  frontend:
    container_name: container-frontend
    build:
      context: ./frontend
    restart: always
    environment:
      LIVE_PATCH: "14.16"
      API_HOST: "http://backend:3001"
    ports:
      - 80:3000

volumes:
  postgres-data: